# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  name: Azure Pipelines
  vmImage: ubuntu-latest
  
pr:
  autoCancel: false  # whether PR updates should cancel in-progress validation runs for the same PR (default is TRUE)
  branches:
    include:
    - master
  drafts: false  # whether draft versions of PRs should fire triggers (default is TRUE)
# trying PRs with necessary comments

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
